version: 3
services:
  redis:
       image: redis
       networks:
               - mynetwork
  nginx:
       image: nginx
       networks:
               - mynetwork
networks: 
         mynetwork: